-- MySQL Script generated by MySQL Workbench
-- sáb 12 nov 2022 07:38:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Disponibilizando um produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Disponibilizando um produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Disponibilizando um produto` (
  `Produto_idProduto` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Fornecedor_idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Entrega` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Entrega` (
  `idEntrega` INT NOT NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Estoque` (
  `idEstoque` INT NOT NULL,
  `local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Frete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Frete` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Frete` (
  `Pedido_idPedido` INT NOT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Entrega_idEntrega`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pagamentos` (
  `idPagamentos` INT NOT NULL,
  `valorPago` VARCHAR(20) NULL,
  `modalidadePagamento` INT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPagamentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` INT NOT NULL,
  `dataPedido` DATETIME NOT NULL,
  `status do pedido` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `idPagamento` INT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PF` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PF` (
  `idPF` INT NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPF`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CPF_UNIQUE` ON `PF` (`CPF` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PJ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PJ` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PJ` (
  `idPJ` INT NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPJ`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CNPJ_UNIQUE` ON `PJ` (`CNPJ` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto` (
  `idProduto` INT NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto_has_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto_has_Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto_has_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produtos por vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produtos por vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produtos por vendedor` (
  `Terceiro - Vendedor_idTerceiro` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`Terceiro - Vendedor_idTerceiro`, `Produto_idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Relação de produto/pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Relação de produto/pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Relação de produto/pedido` (
  `Pedido_idPedido` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Produto_idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Terceiro - Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Terceiro - Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Terceiro - Vendedor` (
  `idTerceiro` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceiro`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
